# netlify.toml
[build]
  # Directory to publish (relative to root of your repo)
  publish = "/"
  
# Redirects and headers are NGINX-style
# For more information see:
# https://docs.netlify.com/routing/redirects/

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
